app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# the Symfony router needs to know the routes provided by the SonataAdminBundle. 
# You can do this by importing them in the routing configuration:
admin_area:
  resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
  prefix: /admin

# Register SonataAdmin custom Routes
# SonataAdminBundle generates routes for the Admin classes
# To load these routes, you have to make sure the routing loader of the SonataAdminBundle is executed:
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

